### ISSUE TITLE
Deal with duplicate USB/Bluetooth devices

### ISSUE THREAD

**Issue by Lvl4Sword** [Lvl4Sword/Killer#14]
Spoofing is an issue, how do we deal with this?

**Comment by GhostofGoes** [comment]
This is something we should definitely deal with at some point. However, I don't think it's a priority until most of the functionality is stable and working across the primary platforms (Linux and Windows).

**Comment by Lvl4Sword** [comment]
This is approached in the new branch, and isn't an issue there.
