### ISSUE TITLE
expand on lsusb [Linux]

### ISSUE THREAD

**Issue by Lvl4Sword** [Lvl4Sword/Killer#2]
```python
import subprocess
import re
a = re.compile(r'\bID \S+ (.+)')
b = re.findall(a, subprocess.check_output('lsusb', shell=False).decode('utf-8'))
print([each.strip() for each in b])
```
Would like to follow more than device ids and this is a good start.

**Comment by Lvl4Sword** [comment]
I'm not sure if this is actually needed. Would like more input and any potential use cases

**Comment by Lvl4Sword** [comment]
@GhostofGoes Do we need this? Would make readability on the whitelists better, but I don't see it helping security.

**Comment by GhostofGoes** [comment]
Remind me what this is again?

**Comment by Lvl4Sword** [comment]
Names of USB devices detected. Something like ``Linux Foundation 2.0 root hub``
