### ISSUE TITLE
Incorrect Config Parsing

### ISSUE THREAD

**Issue by MarkKoz** [Lvl4Sword/Killer#23]
Lists are not parsed properly. There is no concept of a list in configparser. The canonical way of having lists is to delimit the elements and then split the string by the delimiter when parsing.

Also, the default config is missing some keys for windows. Namely `USB_ID_WHITELIST` and `USB_CONNECTED_WHITELIST`.

**Comment by Lvl4Sword** [comment]
Do you want to work on this?

**Comment by MarkKoz** [comment]
I didn't realise this is Windows only. A quick fix would be to just load it as json as is done for POSIX. I may fix this later but I'm busy with logging right now.
