### ISSUE TITLE
Document the configuration file

### ISSUE THREAD

**Issue by GhostofGoes** [Lvl4Sword/Killer#37]
Document of the configuration file parameters, including what they are, what they do and how to set them. Explain any platform quirks, as well as how to get any platform-specific information. For example, how do you get the address of a paired Bluetooth device to add to the white-list on Windows? Linux?

**Comment by 1989gironimo** [comment]
Ok, installed it but I was confused how to get it started. After seeing this issue it makes sense to wait a little before playing with it :)
