### ISSUE TITLE
Full feature set on Mac

### ISSUE THREAD

**Issue by sebmellen** [Lvl4Sword/Killer#4]
Is Mac support in the works? 

I'd be glad to be a tester.

Let me know,
Thanks.

**Comment by Lvl4Sword** [comment]
Give me a few days to clean up the code, start setup of configparser, and finish some Windows stuff and I'll ping you.

**Comment by Lvl4Sword** [comment]
@sebmellen Whenever you have the time, I'd love to get some tests done for Mac!

**Comment by SomethingSomethingUnderscore** [comment]
Am on Mojave and could help with testing.

**Comment by Lvl4Sword** [comment]
@SomethingSomethingUnderscore I didn't see that you had posted on this.
Can you still help with testing?

**Comment by Lvl4Sword** [comment]
The project still needs assistance with support for Mac. Anyone interested and can do testing please post here.

**Comment by SomethingSomethingUnderscore** [comment]
Hi, sorry for the late reply - just saw this. Am still available to help test on Mac.

**Comment by Lvl4Sword** [comment]
@SomethingSomethingUnderscore Can you join the Discord or IRC in the readme so we can talk there?

**Comment by Henrietta1989** [comment]
Does it already run in Mac?

**Comment by Lvl4Sword** [comment]
@Henrietta1989 Not currently as no one has came forward to test. Care to help out?
The IRC/Discord are in the README if you or someone you know would like to assist!

**Comment by Lvl4Sword** [comment]
Due to multiple reasons, Killer is only supported on Linux for the time being.
If this changes in the future, this will be reopened.
