### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by GhostofGoes** [Lvl4Sword/Killer#45]
Create a Vagrantfile with: Windows 7, Windows 10, Ubuntu 16, Ubuntu 18, and Fedora. Any others TBD and can be added as needed. This will make testing much easier since a lot of us don't have access to systems with all of the platforms we want to support, and creating VMs by hand is a pain.

**Comment by Lvl4Sword** [comment]
Vagrant/VMs don't give the ability to test hardware, so this isn't beneficial.
